### ISSUE TITLE
Resource's source data missing

### ISSUE THREAD

**Issue by UglyEugen** [amida-tech/DRE-services#1]
Copied from https://www.pivotaltracker.com/n/projects/1395402/stories/105753582

Uploading data with dre-services still generates DocumentReference resources without links to Binary and Provenance without target data.

**Comment by chaldon** [comment]
Fixed. Check the DocumentReference "content" object:
                "content":[
                    {
                        "attachment":{
                            "contentType":"application/xml",
                            "url":"http://dev.ntrlab.ru:8080/fhir/baseDstu2/Binary/111771/_history/1",
                            "title":"CCD_20131121_ACMA10102495SLTXMWPGMandGoals.xml"
                        }
                    }
