### ISSUE TITLE
swapped lhs & rhs in changes

### ISSUE THREAD

**Issue by igiware** [amida-tech/DRE-services#5]
applying POST: /api/v1/replace/:duplicate, found issue with data:
in change objects 'rhs' & 'lhs' values are swapped (not like described in https://github.com/flitbit/diff).
example change kind 'E':
{
"changeType": "update",
"lhs": {
"resourceType": "Observation",
"id": "4400",
...
"encounter": {
"reference": "Encounter/4274"
},
"valueQuantity": {
"value": 110.22295,
"system": "http://unitsofmeasure.org",
"code": "kg"
}
},
"rhs": {
"resourceType": "Observation",
"id": "56438",
...
"encounter": {
"reference": "Encounter/56284"
},
"valueQuantity": {
"value": 113.98776,
"system": "http://unitsofmeasure.org",
"code": "kg"
}
},
"changes": [
{
"kind": "E",
"path": [
"encounter",
"reference"
],
"lhs": "Encounter/56284", <--- rhs value
"rhs": "Encounter/4274" <-- lhs value
},
{
"kind": "E",
"path": [
"valueQuantity",
"value"
],
"lhs": 113.98776, <-- rhs value
"rhs": 110.22295,<-- lhs value
}
],
"score": 92
}
Same issue with changes type 'N' & 'D' and because they are not symmetric, originally 'N' means 'D', 'D' means 'N' in terms of https://github.com/flitbit/diff
Is it correct or i missed something?

**Comment by mhiner** [comment]
It is unlikely that it is reversed in that the N and D are directly from the deep diff module.  left hand side and right hand side are arbitrary however in that both objects exist in the record already.  i.e.  there is no "new" or "old" object, merely "primary" and "secondary" with order determined by the order in which they are listed in the response from the fhir server.  

I will sort to treat the lowest ID number to be the "existing" record and the higher values being the "new" record though this is a slight misnomer in that both already exist.

**Comment by mhiner** [comment]
New vs Delete is a matter of which side (lhs or rhs) has the change so it is not that both side and N/D are reversed but that the new vs delete are a reflection of the difference from your expected order in lhs and rhs.

**Comment by igiware** [comment]
I'm also using deep-diff. For solving the issue on frontend i've added into app configuration and reverse changes if its set. 
With this solution deepDiff applies selected changes correctly.
