### ISSUE TITLE
POST: /api/v1/replace/:duplicate returns "500 - could not linearizeParams undefined"

### ISSUE THREAD

**Issue by igiware** [amida-tech/DRE-services#6]

**Comment by mhiner** [comment]
Please confirm that your npm modules are up to date.    dre-data should be 0.0.12.

**Comment by mhiner** [comment]
updated to 0.0.13 to make resource order predictable.  going from 12 to 13 should not impact this issue.

**Comment by igiware** [comment]
Now it response 200, but seems nothing changes: data returns after update with  /api/v1/merge/:user
